#!/usr/bin/env bash

set -euo pipefail

log() {
    echo "[TAILSCALE] $1"
}

log "Installing Tailscale..."

sudo pacman -S --needed --noconfirm tailscale

log "Tailscale installed!"
log "To start using Tailscale, run: sudo systemctl enable --now tailscaled && sudo tailscale up"
