#!/usr/bin/env bash

set -euo pipefail

log() {
    echo "[PANDOC] $1"
}

log "Installing Pandoc and LaTeX tools..."

sudo pacman -S --needed --noconfirm \
    pandoc \
    texlive-core \
    texlive-bin \
    texlive-latexextra \
    texlive-fontsrecommended

log "Pandoc and LaTeX tools installed!"
