#!/usr/bin/env bash

set -euo pipefail


echo "Configuring pacman..."

echo "Enabling pacman color and verbose output..."
sudo sed -i 's/^#Color$/Color/' /etc/pacman.conf
sudo sed -i 's/^#VerbosePkgLists$/VerbosePkgLists/' /etc/pacman.conf

echo "Enabling multilib repository..."
sudo sed -i '/^#\[multilib\]$/,/^#Include = \/etc\/pacman.d\/mirrorlist$/ {
    s/^#\[multilib\]$/[multilib]/
    s/^#Include = \/etc\/pacman.d\/mirrorlist$/Include = \/etc\/pacman.d\/mirrorlist/
}' /etc/pacman.conf

echo "Pacman configuration complete!"
echo "Note: Run 'update' script at the end of profile to update all packages"
